import React from "react";
import "../components/layout.css";
import LatestPostsLists from "../components/index/LatestPostsList";
import SidebarLayout from "../components/layouts/SidebarLayout";
import { Link } from "gatsby";
import { metaTitle } from "../constants/metaTitle";
import SEO from "../components/general/SEO";

const FreeMileageTrackerPrivacyPolicy = () => {
  return (
    <div className="w-full mx-4 flex flex-row justify-center items-center">
      <div className={"mx-auto max-w-xl"}>
      <h1 className="font-bold mb-2">Free Mileage Tracker App For Independent Contractors</h1>
      <h1 className="font-bold mb-2">Privacy Policy</h1>
      <p className="mb-1">Last updated: January 27, 2023</p>
      <p className="mb-1">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="mb-1">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the{" "}
        <a
          href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
          target="_blank"
        >
          Free Privacy Policy Generator
        </a>
        .
      </p>
      <h1 className="font-bold mb-2">Interpretation and Definitions</h1>
      <h2 className="font-semibold mb-2">Interpretation</h2>
      <p className="mb-1">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h2 className="font-semibold mb-2">Definitions</h2>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <p className="mb-1">
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>Application</strong> refers to Free Mile Tracker, the
            software program provided by the Company.
          </p>
        </li>
        <li>
          <p className="mb-1"> 
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Free Mile Tracker.
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>Country</strong> refers to: Washington, United States
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </p >
        </li>
        <li>
          <p className="mb-1">
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>Service</strong> refers to the Application.
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p className="mb-1">
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </p>
        </li>
      </ul>
      <h1 className="font-bold mb-2">Collecting and Using Your Personal Data</h1>
      <h2 className="font-semibold mb-2">Types of Data Collected</h2>
      <h3>Personal Data</h3>
      <p className="mb-1">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul>
        <li>Data</li>
      </ul>
      <h3>Usage Data</h3>
      <p className="mb-1">We do not collect any usage data.</p>

      <h1 className="font-bold mb-2">Links to Other Websites</h1>
      <p className="mb-1">
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <p className="mb-1">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <h1 className="font-bold mb-2">Changes to this Privacy Policy</h1>
      <p className="mb-1">
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p >
      <p className="mb-1">
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the &quot;Last
        updated&quot; date at the top of this Privacy Policy.
      </p>
      <p className="mb-1">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h1 className="font-bold mb-2">Contact Us</h1>
      <p className="mb-1">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul>
        <li>By email: m.arriaga.smb@gmail.com</li>
      </ul>
      </div>
    </div>
  );
};

export default FreeMileageTrackerPrivacyPolicy;
